/**
 * Type definitions for Reddit Idea Scraper
 */

/**
 * Reddit post data structure
 */
export interface RedditPost {
  /** Unique post identifier */
  id: string;
  /** Post title */
  title: string;
  /** Post text content */
  selftext: string;
  /** Author username */
  author: string;
  /** Subreddit name */
  subreddit: string;
  /** Upvote score */
  score: number;
  /** Number of comments */
  num_comments: number;
  /** Unix timestamp of creation */
  created_utc: number;
  /** Post URL */
  url: string;
  /** Permalink to post */
  permalink: string;
}

/**
 * Keyword match result
 */
export interface KeywordMatch {
  /** Category of the keyword */
  category: 'money' | 'request' | 'frustration' | 'switching';
  /** The matched keyword */
  keyword: string;
  /** Number of times the keyword appeared */
  count: number;
}

/**
 * Reddit post with keyword analysis
 */
export interface PostWithKeywords extends RedditPost {
  /** Array of keyword matches found */
  keywordMatches: KeywordMatch[];
  /** Calculated keyword score (0-100) */
  keywordScore: number;
}

/**
 * Scored idea from AI analysis
 */
export interface ScoredIdea {
  /** Original Reddit post */
  post: RedditPost;
  /** How clearly the problem is described (0-10) */
  problemScore: number;
  /** Potential for creating an application (0-10) */
  potentialScore: number;
  /** Average of problem and potential scores */
  totalScore: number;
  /** Brief description of the problem */
  problemDescription: string;
  /** Explanation of the scores */
  reasoning: string;
  /** Optional keyword matches */
  keywordMatches?: KeywordMatch[];
  /** Optional keyword score */
  keywordScore?: number;
}

/**
 * MVP specification generated by AI
 */
export interface MVPSpecification {
  /** The scored idea this spec is based on */
  idea: ScoredIdea;
  /** Generated MVP specification in Markdown */
  specification: string;
}

/**
 * Keyword categories configuration
 */
export interface KeywordCategories {
  /** Keywords indicating willingness to pay */
  money: string[];
  /** Keywords indicating request for solution */
  request: string[];
  /** Keywords indicating frustration */
  frustration: string[];
  /** Keywords indicating switching from existing solution */
  switching: string[];
}

/**
 * Application configuration
 */
export interface Config {
  /** List of subreddits to scrape */
  subreddits: string[];
  /** Maximum posts to fetch per subreddit */
  maxPostsPerSubreddit: number;
  /** Minimum upvote score threshold */
  minScoreThreshold: number;
  /** Anthropic API key */
  anthropicApiKey: string;
  /** Model for post analysis */
  modelAnalysis: string;
  /** Model for MVP generation */
  modelMVP: string;
  /** Keyword categories */
  keywords: KeywordCategories;
  /** Clean output directory on startup */
  cleanOutputOnStart: boolean;
}
